use std::{
    collections::BTreeSet,
    fmt::Write as _,
    fs,
    io::Write,
    net::{IpAddr, Ipv4Addr},
    path::PathBuf,
    process::{Command, Stdio},
};

use anyhow::{Context, Result, bail};
use serde::Deserialize;

use crate::config::{AddressFamily, Protocol, SourceMode, Target, ValidatedProfile};

pub const TABLE_V4: &str = "port_forward_v4";
pub const TABLE_V6: &str = "port_forward_v6";

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ResolvedProfile {
    pub validated: ValidatedProfile,
    /// A remote profile's resolved literal destination. Redirect and loopback
    /// profiles leave this unset because their destination is intrinsic.
    pub destination: Option<IpAddr>,
}

impl ResolvedProfile {
    #[must_use]
    pub fn target_port(&self) -> u16 {
        match self.validated.profile.target {
            Target::Remote { port, .. }
            | Target::Redirect { port }
            | Target::LoopbackDnat { port } => port,
        }
    }

    #[must_use]
    pub fn target_address(&self) -> Option<IpAddr> {
        match self.validated.profile.target {
            Target::Remote { .. } => self.destination,
            Target::LoopbackDnat { .. } => Some(IpAddr::V4(Ipv4Addr::LOCALHOST)),
            Target::Redirect { .. } => None,
        }
    }

    #[must_use]
    pub fn is_remote(&self) -> bool {
        matches!(self.validated.profile.target, Target::Remote { .. })
    }
}

/// Records which tables owned by this program are currently installed.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ManagedTablePresence {
    v4: bool,
    v6: bool,
}

impl ManagedTablePresence {
    #[must_use]
    pub const fn new(v4: bool, v6: bool) -> Self {
        Self { v4, v6 }
    }
}

#[must_use]
/// Renders the atomic nftables batch for the supplied resolved profiles.
///
/// Existing project-owned tables are deleted and recreated in the transaction.
/// Tables absent from the current ruleset are simply created. This avoids the
/// `destroy table` command, which is unavailable on older nftables releases,
/// while retaining an atomic replacement on reload.
///
/// # Panics
///
/// Panics when there are more than [`u32::MAX`] profiles or a remote profile
/// has no resolved destination.
pub fn generate_batch(profiles: &[ResolvedProfile], existing: ManagedTablePresence) -> String {
    let mut v4 = Vec::new();
    let mut v6 = Vec::new();
    for (index, profile) in profiles.iter().enumerate() {
        let mark = u32::try_from(index + 1).expect("profiles cannot exceed u32");
        match profile.validated.profile.family {
            AddressFamily::Ipv4 => v4.push((mark, profile)),
            AddressFamily::Ipv6 => v6.push((mark, profile)),
        }
    }
    let mut batch = String::from("# Generated by HY2-MultiPort. Do not edit.\n");
    if existing.v4 {
        let _ = writeln!(batch, "delete table ip {TABLE_V4}");
    }
    if existing.v6 {
        let _ = writeln!(batch, "delete table ip6 {TABLE_V6}");
    }
    render_table(&mut batch, AddressFamily::Ipv4, &v4);
    render_table(&mut batch, AddressFamily::Ipv6, &v6);
    batch
}

fn render_table(batch: &mut String, family: AddressFamily, profiles: &[(u32, &ResolvedProfile)]) {
    let (nft_family, table, address_keyword) = match family {
        AddressFamily::Ipv4 => ("ip", TABLE_V4, "ip"),
        AddressFamily::Ipv6 => ("ip6", TABLE_V6, "ip6"),
    };
    let _ = writeln!(batch, "table {nft_family} {table} {{");
    batch.push_str(
        "  chain prerouting {\n    type nat hook prerouting priority -100; policy accept;\n",
    );
    for (mark, profile) in profiles {
        for protocol in &profile.validated.profile.protocols {
            let condition = rule_condition(profile, *protocol, address_keyword);
            match profile.validated.profile.target {
                Target::Redirect { port } => {
                    let _ = writeln!(
                        batch,
                        "    {condition} redirect to :{port} comment \"hy2-multiport redirect\""
                    );
                }
                Target::LoopbackDnat { port } => {
                    let _ = writeln!(
                        batch,
                        "    {condition} ct mark set {mark} dnat to 127.0.0.1:{port} comment \"hy2-multiport loopback\""
                    );
                }
                Target::Remote { port, .. } => {
                    let address = profile.destination.expect("resolved remote profile");
                    let _ = writeln!(
                        batch,
                        "    {condition} ct mark set {mark} dnat to {} comment \"hy2-multiport remote\"",
                        nft_destination(address, port)
                    );
                }
            }
        }
    }
    batch.push_str("  }\n");

    if profiles.iter().any(|(_, profile)| profile.is_remote()) {
        batch.push_str(
            "  chain forward {\n    type filter hook forward priority 0; policy accept;\n",
        );
        for (mark, profile) in profiles.iter().filter(|(_, profile)| profile.is_remote()) {
            let _ = writeln!(
                batch,
                "    ct mark {mark} ct state established,related accept comment \"hy2-multiport return\""
            );
            let destination = profile.destination.expect("resolved remote profile");
            for protocol in &profile.validated.profile.protocols {
                let _ = writeln!(
                    batch,
                    "    ct mark {mark} {address_keyword} daddr {destination} {protocol} dport {} ct state new accept comment \"hy2-multiport forward\"",
                    profile.target_port(),
                    protocol = protocol.nft_name(),
                );
            }
        }
        batch.push_str("  }\n");
    }

    if family == AddressFamily::Ipv4
        && profiles.iter().any(|(_, profile)| {
            matches!(
                profile.validated.profile.target,
                Target::Remote {
                    source_mode: Some(SourceMode::Masquerade),
                    ..
                }
            )
        })
    {
        batch.push_str(
            "  chain postrouting {\n    type nat hook postrouting priority 100; policy accept;\n",
        );
        for (mark, profile) in profiles {
            if matches!(
                profile.validated.profile.target,
                Target::Remote {
                    source_mode: Some(SourceMode::Masquerade),
                    ..
                }
            ) {
                for protocol in &profile.validated.profile.protocols {
                    let _ = writeln!(
                        batch,
                        "    ct mark {mark} {protocol} masquerade comment \"hy2-multiport masquerade\"",
                        protocol = protocol.nft_name()
                    );
                }
            }
        }
        batch.push_str("  }\n");
    }
    batch.push_str("}\n");
}

fn rule_condition(profile: &ResolvedProfile, protocol: Protocol, keyword: &str) -> String {
    let sources = render_set(&profile.validated.source_cidrs);
    let ports = profile
        .validated
        .listen_ports
        .iter()
        .map(u16::to_string)
        .collect::<Vec<_>>();
    format!(
        "{keyword} daddr {} {keyword} saddr {sources} {} dport {}",
        profile.validated.listen_ip,
        protocol.nft_name(),
        render_set(&ports)
    )
}

fn render_set(values: &[String]) -> String {
    if values.len() == 1 {
        values[0].clone()
    } else {
        format!("{{ {} }}", values.join(", "))
    }
}

fn nft_destination(address: IpAddr, port: u16) -> String {
    match address {
        IpAddr::V4(_) => format!("{address}:{port}"),
        IpAddr::V6(_) => format!("[{address}]:{port}"),
    }
}

#[derive(Clone, Debug)]
pub struct NftCommand {
    executable: PathBuf,
}

impl Default for NftCommand {
    fn default() -> Self {
        Self {
            executable: PathBuf::from("nft"),
        }
    }
}

impl NftCommand {
    #[must_use]
    pub fn with_executable(executable: impl Into<PathBuf>) -> Self {
        Self {
            executable: executable.into(),
        }
    }

    /// Queries the current ruleset and generates a compatible replacement
    /// batch for this program's tables.
    ///
    /// The query is intentionally performed before both `nft -c` and `nft
    /// -f`: a first installation must not contain `delete table`, while a
    /// reload must delete only tables that are known to exist.
    ///
    /// # Errors
    ///
    /// Returns an error when `nft` cannot run, its table list cannot be read,
    /// or it does not return valid JSON.
    pub fn prepare_batch(&self, profiles: &[ResolvedProfile]) -> Result<String> {
        Ok(generate_batch(profiles, self.managed_table_presence()?))
    }

    fn managed_table_presence(&self) -> Result<ManagedTablePresence> {
        let output = Command::new(&self.executable)
            .args(["-j", "list", "tables"])
            .output()
            .with_context(|| format!("cannot execute {}", self.executable.display()))?;
        if !output.status.success() {
            bail!(
                "cannot inspect project nftables tables: {}",
                String::from_utf8_lossy(&output.stderr).trim()
            );
        }
        let ruleset: NftRuleset =
            serde_json::from_slice(&output.stdout).context("nft returned invalid JSON")?;
        Ok(ManagedTablePresence::new(
            ruleset.nftables.iter().any(|item| {
                item.table
                    .as_ref()
                    .is_some_and(|table| table.family == "ip" && table.name == TABLE_V4)
            }),
            ruleset.nftables.iter().any(|item| {
                item.table
                    .as_ref()
                    .is_some_and(|table| table.family == "ip6" && table.name == TABLE_V6)
            }),
        ))
    }

    /// Checks that another base chain does not own a conflicting hook.
    ///
    /// # Errors
    ///
    /// Returns an error when `nft` cannot run, its ruleset cannot be read as
    /// JSON, or an external base chain uses a managed hook.
    pub fn reject_external_hook_conflicts(&self) -> Result<()> {
        let conflicts = self.external_hook_conflicts()?;
        if conflicts.is_empty() {
            Ok(())
        } else {
            bail!(
                "external nftables base-chain/hook conflict; refusing to guess ordering: {}",
                conflicts.join(", ")
            );
        }
    }

    /// Lists external base chains that use hooks owned by port forwarding.
    /// This is strictly read-only and is shared by daemon preflight and the
    /// operator-facing doctor command.
    ///
    /// # Errors
    ///
    /// Returns an error when `nft` cannot run or its JSON ruleset cannot be
    /// inspected.
    pub fn external_hook_conflicts(&self) -> Result<Vec<String>> {
        let output = Command::new(&self.executable)
            .args(["-j", "list", "ruleset"])
            .output()
            .with_context(|| format!("cannot execute {}", self.executable.display()))?;
        if !output.status.success() {
            bail!(
                "cannot inspect existing nftables ruleset: {}",
                String::from_utf8_lossy(&output.stderr).trim()
            );
        }
        let ruleset: NftRuleset =
            serde_json::from_slice(&output.stdout).context("nft returned invalid JSON")?;
        let conflicts: BTreeSet<_> =
            ruleset
                .nftables
                .into_iter()
                .filter_map(|item| item.chain)
                .filter(|chain| {
                    chain.hook.as_deref().is_some_and(|hook| {
                        matches!(hook, "prerouting" | "forward" | "postrouting")
                    }) && !matches!(chain.table.as_str(), TABLE_V4 | TABLE_V6)
                })
                .map(|chain| {
                    format!(
                        "{} {} hook {}",
                        chain.family,
                        chain.table,
                        chain.hook.unwrap_or_default()
                    )
                })
                .collect();
        Ok(conflicts.into_iter().collect())
    }

    /// Checks an nftables batch without applying it.
    ///
    /// # Errors
    ///
    /// Returns an error when `nft` cannot run or rejects `batch` during its
    /// syntax and semantic check.
    pub fn check(&self, batch: &str) -> Result<()> {
        self.run(&["-c", "-f", "-"], batch, "nft preflight")
    }

    /// Applies an nftables batch atomically.
    ///
    /// # Errors
    ///
    /// Returns an error when `nft` cannot run or rejects `batch`.
    pub fn apply(&self, batch: &str) -> Result<()> {
        self.run(&["-f", "-"], batch, "nft atomic apply")
    }

    fn run(&self, args: &[&str], batch: &str, action: &str) -> Result<()> {
        let mut child = Command::new(&self.executable)
            .args(args)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .with_context(|| {
                format!("cannot execute {} for {action}", self.executable.display())
            })?;
        child
            .stdin
            .take()
            .context("nft stdin unavailable")?
            .write_all(batch.as_bytes())?;
        let output = child.wait_with_output()?;
        if output.status.success() {
            Ok(())
        } else {
            bail!(
                "{action} failed: {}",
                String::from_utf8_lossy(&output.stderr).trim()
            )
        }
    }
}

#[derive(Deserialize)]
struct NftRuleset {
    nftables: Vec<NftRulesetItem>,
}

#[derive(Deserialize)]
struct NftRulesetItem {
    table: Option<NftTable>,
    chain: Option<NftChain>,
}

#[derive(Deserialize)]
struct NftTable {
    family: String,
    name: String,
}

#[derive(Deserialize)]
struct NftChain {
    family: String,
    table: String,
    hook: Option<String>,
}

#[derive(Clone, Debug)]
pub struct NetworkInspector {
    ip_executable: PathBuf,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RouteLocalnetAdjustment {
    pub interface: String,
    pub original: bool,
}

impl NetworkInspector {
    #[must_use]
    pub fn with_ip_executable(ip_executable: impl Into<PathBuf>) -> Self {
        Self {
            ip_executable: ip_executable.into(),
        }
    }

    /// Checks local interface, route, and loopback forwarding prerequisites.
    ///
    /// # Errors
    ///
    /// Returns an error when `ip` cannot inspect interfaces or IPv6 routes, a
    /// listener belongs to zero or multiple interfaces, or a `route_localnet`
    /// value cannot be read.
    pub fn preflight(&self, profiles: &[ResolvedProfile]) -> Result<Vec<RouteLocalnetAdjustment>> {
        let interfaces = self.local_interfaces()?;
        let mut loopback_interfaces = BTreeSet::new();
        for profile in profiles {
            let matches = interfaces
                .iter()
                .filter(|interface| interface.addresses.contains(&profile.validated.listen_ip))
                .map(|interface| interface.name.clone())
                .collect::<Vec<_>>();
            if matches.len() != 1 {
                bail!(
                    "profile {:?} listen address {} must belong to exactly one local interface (found {})",
                    profile.validated.profile.name,
                    profile.validated.listen_ip,
                    matches.len()
                );
            }
            if let Some(destination) = profile
                .destination
                .filter(|_| profile.validated.profile.family == AddressFamily::Ipv6)
            {
                self.check_ipv6_route(destination)?;
            }
            if matches!(
                profile.validated.profile.target,
                Target::LoopbackDnat { .. }
            ) {
                loopback_interfaces.insert(matches[0].clone());
            }
        }
        loopback_interfaces
            .into_iter()
            .map(|interface| {
                let value = route_localnet_path(&interface)?;
                let original = fs::read_to_string(&value)
                    .with_context(|| format!("cannot read {}", value.display()))?
                    .trim()
                    == "1";
                Ok(RouteLocalnetAdjustment {
                    interface,
                    original,
                })
            })
            .collect()
    }

    /// Enables `route_localnet` for every listed interface.
    ///
    /// # Errors
    ///
    /// Returns an error when an interface name is unsafe or its kernel setting
    /// cannot be written.
    pub fn enable_route_localnet(&self, adjustments: &[RouteLocalnetAdjustment]) -> Result<()> {
        for adjustment in adjustments {
            fs::write(route_localnet_path(&adjustment.interface)?, "1\n").with_context(|| {
                format!("cannot enable route_localnet on {}", adjustment.interface)
            })?;
        }
        Ok(())
    }

    /// Restores `route_localnet` to each interface's recorded value.
    ///
    /// # Errors
    ///
    /// Returns an error when an interface name is unsafe or its kernel setting
    /// cannot be written.
    pub fn restore_route_localnet(&self, adjustments: &[RouteLocalnetAdjustment]) -> Result<()> {
        for adjustment in adjustments {
            let value = if adjustment.original { "1\n" } else { "0\n" };
            fs::write(route_localnet_path(&adjustment.interface)?, value).with_context(|| {
                format!("cannot restore route_localnet on {}", adjustment.interface)
            })?;
        }
        Ok(())
    }

    fn local_interfaces(&self) -> Result<Vec<LocalInterface>> {
        let output = Command::new(&self.ip_executable)
            .args(["-j", "address", "show"])
            .output()
            .with_context(|| format!("cannot execute {}", self.ip_executable.display()))?;
        if !output.status.success() {
            bail!(
                "ip address inspection failed: {}",
                String::from_utf8_lossy(&output.stderr).trim()
            );
        }
        let raw: Vec<IpInterface> =
            serde_json::from_slice(&output.stdout).context("ip returned invalid address JSON")?;
        Ok(raw
            .into_iter()
            .map(|interface| LocalInterface {
                name: interface.ifname,
                addresses: interface
                    .addr_info
                    .into_iter()
                    .filter_map(|address| address.local.parse().ok())
                    .collect(),
            })
            .collect())
    }

    fn check_ipv6_route(&self, destination: IpAddr) -> Result<()> {
        let output = Command::new(&self.ip_executable)
            .args(["-6", "route", "get", &destination.to_string()])
            .output()
            .with_context(|| format!("cannot execute {}", self.ip_executable.display()))?;
        if output.status.success() {
            Ok(())
        } else {
            bail!(
                "IPv6 route preflight for {destination} failed: {}",
                String::from_utf8_lossy(&output.stderr).trim()
            )
        }
    }
}

impl Default for NetworkInspector {
    fn default() -> Self {
        Self {
            ip_executable: PathBuf::from("ip"),
        }
    }
}

#[derive(Deserialize)]
struct IpInterface {
    ifname: String,
    #[serde(default)]
    addr_info: Vec<IpAddress>,
}

#[derive(Deserialize)]
struct IpAddress {
    local: String,
}

struct LocalInterface {
    name: String,
    addresses: Vec<IpAddr>,
}

fn route_localnet_path(interface: &str) -> Result<PathBuf> {
    if interface.is_empty()
        || !interface
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-' | b'.'))
    {
        bail!("unsafe interface name {interface:?}");
    }
    Ok(PathBuf::from("/proc/sys/net/ipv4/conf")
        .join(interface)
        .join("route_localnet"))
}

#[cfg(test)]
mod tests {
    use crate::config::Config;

    use super::*;

    fn profile(toml: &str, destination: Option<&str>) -> ResolvedProfile {
        let validated = Config::from_toml(toml)
            .unwrap()
            .validate()
            .unwrap()
            .remove(0);
        ResolvedProfile {
            validated,
            destination: destination.map(str::parse).transpose().unwrap(),
        }
    }

    #[test]
    fn generates_exact_v4_remote_dnat_forward_and_masquerade() {
        let profile = profile(
            r#"
schema_version = 1
[[profiles]]
name = "v4"
family = "ipv4"
listen_address = "192.0.2.10"
protocols = ["tcp", "udp"]
source_cidrs = ["192.0.2.0/24", "198.51.100.0/24"]
[profiles.listen_ports]
ports = [2053, 3053]
[profiles.target]
kind = "remote"
host = "origin.test"
port = 53
source_mode = "masquerade"
"#,
            Some("10.0.0.53"),
        );
        let rules = generate_batch(&[profile], ManagedTablePresence::default());
        assert!(rules.contains("ip daddr 192.0.2.10 ip saddr { 192.0.2.0/24, 198.51.100.0/24 } tcp dport { 2053, 3053 } ct mark set 1 dnat to 10.0.0.53:53"));
        assert!(rules.contains("ct mark 1 ip daddr 10.0.0.53 tcp dport 53 ct state new accept"));
        assert!(rules.contains("ct mark 1 tcp masquerade"));
        assert!(rules.contains("ct mark 1 udp masquerade"));
    }

    #[test]
    fn ipv6_dnat_has_no_nat66_or_postrouting() {
        let profile = profile(
            r#"
schema_version = 1
[[profiles]]
name = "v6"
family = "ipv6"
listen_address = "2001:db8::10"
protocols = ["udp"]
[profiles.listen_ports]
ports = [2053]
[profiles.target]
kind = "remote"
host = "origin.test"
port = 53
"#,
            Some("2001:db8:1::53"),
        );
        let rules = generate_batch(&[profile], ManagedTablePresence::default());
        assert!(rules.contains("dnat to [2001:db8:1::53]:53"));
        assert!(!rules.contains("masquerade"));
        assert!(!rules.contains("postrouting"));
    }

    #[test]
    fn redirect_and_opted_in_loopback_are_distinct() {
        let redirect = profile(
            r#"
schema_version = 1
[[profiles]]
name = "r"
family = "ipv4"
listen_address = "192.0.2.10"
protocols = ["udp"]
[profiles.listen_ports]
ports = [53]
[profiles.target]
kind = "redirect"
port = 5353
"#,
            None,
        );
        let loopback = profile(
            r#"
schema_version = 1
[[profiles]]
name = "l"
family = "ipv4"
listen_address = "192.0.2.11"
protocols = ["tcp"]
allow_route_localnet = true
[profiles.listen_ports]
ports = [443]
[profiles.target]
kind = "loopback-dnat"
port = 8443
"#,
            None,
        );
        let rules = generate_batch(&[redirect, loopback], ManagedTablePresence::default());
        assert!(rules.contains("redirect to :5353"));
        assert!(rules.contains("dnat to 127.0.0.1:8443"));
    }

    #[test]
    fn only_deletes_managed_tables_that_already_exist() {
        let no_tables = generate_batch(&[], ManagedTablePresence::default());
        assert!(!no_tables.contains("delete table"));

        let v4_only = generate_batch(&[], ManagedTablePresence::new(true, false));
        assert!(v4_only.contains("delete table ip port_forward_v4"));
        assert!(!v4_only.contains("delete table ip6 port_forward_v6"));

        let both = generate_batch(&[], ManagedTablePresence::new(true, true));
        assert!(both.contains("delete table ip port_forward_v4"));
        assert!(both.contains("delete table ip6 port_forward_v6"));
        assert!(!both.contains("destroy table"));
    }

    #[test]
    fn uses_numeric_base_chain_priorities() {
        let profile = profile(
            r#"
schema_version = 1
[[profiles]]
name = "v4"
family = "ipv4"
listen_address = "192.0.2.10"
protocols = ["tcp"]
[profiles.listen_ports]
ports = [443]
[profiles.target]
kind = "remote"
host = "origin.test"
port = 8443
source_mode = "masquerade"
"#,
            Some("198.51.100.53"),
        );
        let rules = generate_batch(&[profile], ManagedTablePresence::default());
        assert!(rules.contains("hook prerouting priority -100"));
        assert!(rules.contains("hook forward priority 0"));
        assert!(rules.contains("hook postrouting priority 100"));
    }

    #[test]
    fn identifies_external_hooks_from_nft_json() {
        let json = r#"{"nftables":[{"chain":{"family":"ip","table":"filter","name":"input","type":"filter","hook":"forward"}},{"chain":{"family":"ip","table":"port_forward_v4","name":"forward","hook":"forward"}}]}"#;
        let ruleset: NftRuleset = serde_json::from_str(json).unwrap();
        assert_eq!(ruleset.nftables.len(), 2);
        let path = route_localnet_path("eth0.100").unwrap();
        assert!(path.ends_with("eth0.100/route_localnet"));
        assert!(route_localnet_path("../../oops").is_err());
    }
}
